# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\EventListener\BoxListener:
        public: true
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
        
    AppBundle\Menu\Builder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main}
            
    Nines\UserBundle\Menu\Builder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}
            
    AppBundle\Services\:
        resource: '../../src/AppBundle/Services'
        public: true
            
    AppBundle\Services\FilePaths:
        arguments: ['@logger', '%kernel.project_dir%', '%lom.download_dir%']
        
