# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\UserBundle\:
        resource: '../../src/Nines/UserBundle/*'
        exclude: '../../src/Nines/UserBundle/{Entity,Repository,Resources,Tests}'

    Nines\UserBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Resources,Tests}'

    AppBundle\Command\Lockss\BoxStatusCommand:
        arguments:
            $sizeWarning: '%lom.boxstatus.sizewarning%'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\BoxListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
        calls:
            - { method: setLogger, arguments: ['@logger'] }

    AppBundle\EventListener\SwordExceptionListener:
        arguments:
            $env: "%kernel.environment%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: kernel.event_listener, event: kernel.controller }

    AppBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main}

    AppBundle\Services\AuManager:
        calls:
            - { method: setLogger, arguments: ['@logger'] }

    AppBundle\Services\ConfigExporter:
        arguments:
            $ausPerTitleDb: '%lom.aus_per_titledb%'

    AppBundle\Services\ConfigUpdater:
        arguments:
            $ausPerTitleDb: '%lom.aus_per_titledb%'

    AppBundle\Services\FilePaths:
        arguments:
            $root: '%kernel.project_dir%'
            $downloadDir: '%lom.download_dir%'

    AppBundle\Services\BoxNotifier:
        arguments:
            $sender: '%lom.boxstatus.sender%'
            $contact: '%lom.boxstatus.contact%'

