monolog:
    channels: [ 'sword', 'lockss', 'soap' ]
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ["!event", "!doctrine", "!console", "!lockss", "!sword"]
            max_files: 1
        lockss:
            level: notice
            type: rotating_file
            path: '%kernel.logs_dir%/lockss-%kernel.environment%.log'
            channels: [ 'lockss' ]
            max_files: 1
        soap:
            level: notice
            type: rotating_file
            path: '%kernel.logs_dir%/soap-%kernel.environment%.log'
            channels: [ 'soap' ]
            max_files: 1
        sword:
            level: notice
            type: rotating_file
            path: '%kernel.logs_dir%/sword-%kernel.environment%.log'
            channels: [ 'sword' ]
            max_files: 1
